spring.application.name=taskmanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=postgres
spring.datasource.password=Kharbita+2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret-key=5b7d2f4a9c8e1f6b3a7d9e2c4f8a1b6d5e9f2a7c3b8d1e6f4a9c2b7d8e1f6a3
security.jwt.expiration=86400000